#!/bin/bash
sudo apt update
sudo apt install libpq-dev
sudo apt-get install build-essential
sudo apt-get -y install python3-pip
cd /home/ec2-user/app/sbrb-backend
sudo apt install postgresql
sudo pip3 install -r requirements.txt