name: Check PR Name, Lint Frontend, Format Backend, Run Backend Tests

on:
  push:
    branches:
      - main

jobs:
  backend-format:
    needs: [backend-test, frontend-lint]
    runs-on: ubuntu-latest
    permissions: write-all
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies for formatting
        working-directory: sbrb-backend
        run: pip install black isort

      - name: Format backend code
        working-directory: sbrb-backend
        run: |
          isort .
          black .

      - name: Check for changes
        id: check_changes
        run: |
          git add sbrb-backend
          if git diff-index --quiet HEAD; then
            echo "No changes found"
            echo "::set-output name=changes::false"
          else
            echo "Changes found"
            echo "::set-output name=changes::true"
          fi

      - name: Commit formatted code
        if: steps.check_changes.outputs.changes == 'true'
        working-directory: sbrb-backend
        run: |
          git config user.name "Github Actions"
          git config user.email "actions.github.com"
          git commit -m "Auto-format code with Black"
          git show-ref
          git push origin ${{ github.head_ref }}