name: Check PR Name, Lint Frontend, Run Backend Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  NODE_VERSION: "18.x"

jobs:
  pr-naming:
    permissions:
      pull-requests: read
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Check if PR title follows conventional commits specs
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  frontend-lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install frontend dependencies
        working-directory: sbrb-frontend
        run: npm ci

      - name: Lint frontend code
        working-directory: sbrb-frontend
        run: npm run lint

      - name: Lint frontend code
        working-directory: sbrb-frontend
        run: npm run check-format

  backend-test:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: sbrb-backend
        run: pip install -r requirements.txt

      - name: Run backend tests
        working-directory: sbrb-backend
        run: pytest -v
